# pyproject.toml
[tool.black]
line-length = 88 # The standard length Black enforces
target-version = ['py314']

[tool.mypy]
# Enable strict checks for high-integrity codebases
strict = true

[tool.flake8]
max-line-length = 88
# Ignore specific errors if needed (e.g., E203 is often ignored when using Black)
ignore = ['E203']
exclude = ['.git', '__pycache__', 'venv', 'docs', 'migrations']